### PR TITLE
pull request build should use locked CRR version

### PR DESCRIPTION
**Pull request by v-minnli**

### CODE REVIEW

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[36f0930](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16989/commits/36f09305c78a70f9aaf49fd77042a11ae2286796)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C21%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201903210745240208-16989%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NMnUp6fvg4ewN%2BkRf0lgbPnlklRBL0rV9atFYXB6tE4%3D&st=2019-03-21T07%3A41%3A38Z&se=2019-04-21T07%3A46%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
OPS Build status updates of commit _[36f0930](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16989/commits/36f09305c78a70f9aaf49fd77042a11ae2286796)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C21%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201903210754586446-16989%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PjAocPXPpnA7aCQnxFpIsWRrXdDgLyaP9ObsCMi841E%3D&st=2019-03-21T07%3A51%3A44Z&se=2019-04-21T07%3A56%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
OPS Build status updates of commit _[0191a69](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16989/commits/0191a6924810952d90be64a13c56acf315979930)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[E2E_DocsBranch_Prod_Dynamic/index.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest-v3/E2E_DocsBranch_Prod_Dynamic/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic/index?branch=pr-en-us-16989) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C21%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201903210839412825-16989%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4nw6KVzSpJIB1yJdrqlNrX904%2Fmydqd6UP7SKpYJGPs%3D&st=2019-03-21T08%3A36%3A44Z&se=2019-04-21T08%3A41%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
OPS Build status updates of commit _[0191a69](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16989/commits/0191a6924810952d90be64a13c56acf315979930)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[E2E_DocsBranch_Prod_Dynamic/index.md](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest-v3/E2E_DocsBranch_Prod_Dynamic/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/E2E_DocsBranch_Prod_Dynamic/index?branch=pr-en-us-16989) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C21%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201903210843548129-16989%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=6N9YITRHfWgVt6iK62Kr3FIOyYMefrU%2F4t9mSiLjd3c%3D&st=2019-03-21T08%3A40%3A15Z&se=2019-04-21T08%3A45%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[2c69ba1](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16989/commits/2c69ba1ab8505e62bcaa21313a6eb5e75945b3d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C21%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201903210850571628-16989%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kOFDm3a8A0lEi8h9417lNjnBqCy5YlNXvFnbP3ili8g%3D&st=2019-03-21T08%3A47%3A41Z&se=2019-04-21T08%3A52%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[2c69ba1](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16989/commits/2c69ba1ab8505e62bcaa21313a6eb5e75945b3d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C21%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201903210858115409-16989%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TpXOKGJqcN8GttfpgHI%2BmcU0aoPQkT%2B1gUqLDFpMNU0%3D&st=2019-03-21T08%3A55%3A05Z&se=2019-04-21T09%3A00%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
Docs Build status updates of commit _[e549f25](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16989/commits/e549f25a5df0558c836022156357469623ad5ca6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C6%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201905060831114134-16989%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=9CkhdK3R2j1pRS8mFhUSW8PhXR3b3nIPoLE26lXutzQ%3D&st=2019-05-06T08%3A26%3A42Z&se=2019-06-06T08%3A31%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
