### PR TITLE
pull request build should use locked CRR version

### PR DESCRIPTION
**Pull request by v-minnli**

### CODE REVIEW

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[fdb99ca](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16984/commits/fdb99cabf8775ffe93ea2df6ffd13bdfdd3698a2)_: 

:clock10: **Preparing**: average preparing time is _43 sec(s)_

**Comment by v-susu** [comment]
OPS Build status updates of commit _[fdb99ca](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16984/commits/fdb99cabf8775ffe93ea2df6ffd13bdfdd3698a2)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by v-peliao** [comment]
OPS Build status updates of commit _[fdb99ca](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16984/commits/fdb99cabf8775ffe93ea2df6ffd13bdfdd3698a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C19%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201902190859526419-16984%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uERVzbsDYBSJRKLTgcU3SF2qSlWetBk5d6drBUSVuVk%3D&st=2019-02-19T08%3A55%3A48Z&se=2019-03-22T09%3A00%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[fdb99ca](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16984/commits/fdb99cabf8775ffe93ea2df6ffd13bdfdd3698a2)_: 

:clock10: **Preparing**: average preparing time is _43 sec(s)_

**Comment by v-susu** [comment]
OPS Build status updates of commit _[fdb99ca](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16984/commits/fdb99cabf8775ffe93ea2df6ffd13bdfdd3698a2)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by v-peliao** [comment]
OPS Build status updates of commit _[fdb99ca](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16984/commits/fdb99cabf8775ffe93ea2df6ffd13bdfdd3698a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C19%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201902190904244720-16984%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0Zsa%2BCcke3YrQveGhsX63qltBF3KvDMCVE3pXcgs7Do%3D&st=2019-02-19T09%3A00%3A39Z&se=2019-03-22T09%3A05%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[fdb99ca](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16984/commits/fdb99cabf8775ffe93ea2df6ffd13bdfdd3698a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C19%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201903190913128177-16984%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Pj9eWARrtfzI5CnOgm812OmRBtes4kSn2sZYIREor2U%3D&st=2019-03-19T09%3A09%3A52Z&se=2019-04-19T09%3A14%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
OPS Build status updates of commit _[fdb99ca](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16984/commits/fdb99cabf8775ffe93ea2df6ffd13bdfdd3698a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C21%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201903210819314942-16984%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=y1KBvKO54If6thIKwgUy7dQgTqnBWbwP%2Fqvnaav3X5o%3D&st=2019-03-21T08%3A15%3A45Z&se=2019-04-21T08%3A20%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[fdb99ca](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16984/commits/fdb99cabf8775ffe93ea2df6ffd13bdfdd3698a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C21%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201903210826519027-16984%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=41OGjcbRkL3TtwpTKYFYjbfYOflLWRrO7p5g6pwCuh4%3D&st=2019-03-21T08%3A23%3A33Z&se=2019-04-21T08%3A28%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[fdb99ca](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16984/commits/fdb99cabf8775ffe93ea2df6ffd13bdfdd3698a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C1%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201904010732211258-16984%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CFwVIACvzkvLbIHTzlHxcBrCkDhBfJWsBnFInvwdkC8%3D&st=2019-04-01T07%3A29%3A13Z&se=2019-05-02T07%3A34%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
Docs Build status updates of commit _[fdb99ca](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/pull/16984/commits/fdb99cabf8775ffe93ea2df6ffd13bdfdd3698a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/E2E_DocsBranch_Prod_Dynamic/blob/crr-pullRequest/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C5%5C28%5C70db20ec-e9da-7d89-0cf0-4d250dac361e%5CPullRequest%5C201905280157412435-16984%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IAdoK77aKlgbdgSIYzgrqslBacwrnahWwtFC195%2B9JQ%3D&st=2019-05-28T01%3A53%3A36Z&se=2019-06-28T01%3A58%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
